name = "ribla-editores"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your environment variables here or in the Cloudflare Dashboard

# Pages deployment
pages_build_output_dir = ".vercel/output/static"
